all:
  children:
    fortigate:
      hosts:
        fortigate-lab:
          ansible_host: 192.168.100.10

          # Verbindung
          ansible_connection: httpapi
          ansible_network_os: fortinet.fortios.fortios

          # Auth über ENV (kein Secret im Repo!)
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_httpapi_port: 443

          ansible_httpapi_session_key:
            access_token: "{{ lookup('env', 'FORTIOS_ACCESS_TOKEN') }}"
